### ISSUE TITLE
apiVersion: extensions/v1beta1 is not recognized

### ISSUE THREAD

**Issue by cypressious** [tinselspoon/intellij-kubernetes#12]
The following file is not recognized

```yml
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: foo-api-deployment
  labels:
    name: foo-api-deployment
    app: foo-api-runtime
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: foo-api-runtime
    spec:
      containers:
      - name: foo-api-host
        image: gcr.io/foo/foo-api:59f923238233fd32a802367bca0c8adf1422090e
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: foo-api-host-svc
  labels:
    app: foo-api-runtime
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: foo-api-runtime
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-api
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: foo-api-ip		
spec:
  tls:
  - hosts:
    - api.foo.com
    secretName: foo-api-bls-cert
  rules:
  - host: api.foo.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: foo-api-host-svc
          servicePort: 80
         
```
